--- 12.1.0 权威控件方法名（由 lycheedev source inspect 从 Blizzard_APIDocumentationGenerated 提取）
-- 来源：wow-ui-source @ 09b9db7948abc9b9648dedaab51eb0cf3ee67b31（retail live）
-- 用途：离线冒烟测试据此拒绝不存在的 Frame 方法，避免 EnableDrag 这类错误再次溜过。
-- 重新生成：见 PERFORMANCE.md 的「权威方法表」。
return {
  a = true,AbortDrag = true,AddAccessRestrictions = true,AddForbiddenAspects = true,AddHistoryLine = true,
  AddMaskTexture = true,AddRoleset = true,AddSecretAspect = true,AdjustPointsOffset = true,alpha = true,
  alphabet = true,alphaIfFalse = true,alphaIfTrue = true,altMode = true,alwaysStartFromMouse = true,
  anchorIndex = true,areas = true,arguments = true,aspect = true,aspects = true,asset = true,atlas = true,
  attributeName = true,autoFocus = true,bias = true,bindingType = true,blendMode = true,blocking = true,
  bottom = true,button = true,buttons = true,buttonState = true,calculated = true,
  CalculateScreenAreaFromCharacterSpan = true,canAccess = true,CanBeAccessedInContext = true,canChange = true,
  CanChangeAttribute = true,canChangeAttributes = true,CanChangeProtectedState = true,CanNonSpaceWrap = true,
  canPropagate = true,CanPropagateMouseClicks = true,CanPropagateMouseMotion = true,CanWordWrap = true,
  cb = true,cell = true,cellHeight = true,cellWidth = true,characterIndex = true,checked = true,
  children = true,clampedToScreen = true,ClearAllPoints = true,ClearAlphaGradient = true,
  ClearAttribute = true,ClearAttributes = true,ClearDisabledTexture = true,cleared = true,ClearFocus = true,
  ClearHighlightText = true,ClearHighlightTexture = true,ClearHistory = true,ClearNormalTexture = true,
  clearOtherKeys = true,ClearParentKey = true,ClearPoint = true,ClearPointsOffset = true,
  ClearPushedTexture = true,ClearRadialProgressBar = true,ClearScripts = true,ClearSVG = true,
  ClearText = true,ClearTextureSlice = true,ClearVertexOffsets = true,Click = true,clipsChildren = true,
  collapsesLayout = true,CollapsesLayout = true,colorA = true,colorB = true,colorG = true,colorIfFalse = true,
  colorIfTrue = true,colorR = true,CopyExternalLink = true,CopyFontObject = true,count = true,
  countInvisibleLetters = true,CreateAnimationGroup = true,CreateFontString = true,CreateLine = true,
  CreateMaskTexture = true,CreateTexture = true,CreateVectorGraphics = true,cursorBlinkSpeedSec = true,
  cursorPosition = true,debugName = true,delegate = true,DeleteCookies = true,desaturate = true,
  desaturated = true,DesaturateHierarchy = true,desaturation = true,direction = true,Disable = true,
  DisableDrawLayer = true,displayText = true,DoesClipChildren = true,DoesHyperlinkPropagateToParent = true,
  dontSave = true,doResize = true,drawLayer = true,duration = true,effectiveAlpha = true,
  effectiveScale = true,Enable = true,enable = true,enabled = true,EnableDrawLayer = true,
  EnableGamePadButton = true,EnableGamePadStick = true,EnableKeyboard = true,EnableMouse = true,
  EnableMouseMotion = true,EnableMouseWheel = true,eventName = true,excludeRoot = true,
  ExecuteAttribute = true,feather = true,fieldSize = true,file = true,fillStyle = true,filterMode = true,
  FindCharacterIndexAtCoordinate = true,fixedColor = true,flags = true,flatten = true,font = true,
  fontFile = true,fontHeight = true,fontString = true,FrameEventCallbackType = true,frameLevel = true,
  frameScale = true,GetAccessRestrictions = true,GetAlpha = true,GetAlphaGradient = true,
  GetAltArrowKeyMode = true,GetAnimationGroups = true,GetAtlas = true,GetAttribute = true,GetBlendMode = true,
  GetBlinkSpeed = true,GetBottom = true,GetBoundsRect = true,GetButtonState = true,GetCenter = true,
  GetChecked = true,GetCheckedTexture = true,GetChildren = true,GetClampRectInsets = true,
  GetCursorPosition = true,GetDebugName = true,GetDesaturation = true,GetDisabledCheckedTexture = true,
  GetDisabledFontObject = true,GetDisabledTexture = true,GetDisplayText = true,GetDontSavePosition = true,
  GetDrawLayer = true,GetEffectiveAlpha = true,GetEffectivelyFlattensRenderLayers = true,
  GetEffectiveScale = true,GetEndPoint = true,GetFieldSize = true,GetFillStyle = true,
  GetFlattensRenderLayers = true,GetFont = true,GetFontHeight = true,GetFontObject = true,
  GetFontObjectForAlphabet = true,GetFontString = true,GetForbiddenAspects = true,GetFrameLevel = true,
  GetFrameStrata = true,GetHeight = true,GetHighestFrameLevel = true,GetHighlightColor = true,
  GetHighlightFontObject = true,GetHighlightTexture = true,GetHistoryLines = true,GetHitRectInsets = true,
  GetHitRectThickness = true,GetHorizontalScroll = true,GetHorizontalScrollRange = true,GetHorizTile = true,
  GetHyperlinksEnabled = true,GetID = true,GetIndentedWordWrap = true,GetInheritableForbiddenAspects = true,
  GetInputLanguage = true,GetInterpolatedValue = true,GetJustifyH = true,GetJustifyV = true,GetLeft = true,
  GetLineHeight = true,GetMaskTexture = true,GetMaxBytes = true,GetMaxLetters = true,GetMaxLines = true,
  GetMinMaxValues = true,GetMotionScriptsWhileDisabled = true,GetName = true,GetNormalFontObject = true,
  GetNormalTexture = true,GetNumber = true,GetNumChildren = true,GetNumLetters = true,GetNumLines = true,
  GetNumMaskTextures = true,GetNumPoints = true,GetNumRegions = true,GetObeyStepOnDrag = true,
  GetObjectTable = true,GetObjectType = true,GetOnUpdateMode = true,GetOrientation = true,GetParent = true,
  GetParentKey = true,GetPoint = true,GetPointByName = true,GetPropagateKeyboardInput = true,
  GetPushedTextOffset = true,GetPushedTexture = true,GetRadialProgressBarEndOffset = true,
  GetRadialProgressBarFeather = true,GetRadialProgressBarPercent = true,GetRadialProgressBarReverse = true,
  GetRadialProgressBarStartOffset = true,GetRaisedFrameLevel = true,GetRect = true,GetRegions = true,
  GetRenderMode = true,GetResizeBounds = true,GetReverseFill = true,GetRight = true,GetRolesetNames = true,
  GetRotatesTexture = true,GetRotation = true,GetScale = true,GetScaleAnimationMode = true,
  GetScaledRect = true,GetScript = true,GetScrollChild = true,GetShadowColor = true,GetShadowOffset = true,
  GetSize = true,GetSmoothScaling = true,GetSourceLocation = true,GetSpacing = true,GetStartPoint = true,
  GetStatusBarColor = true,GetStatusBarDesaturation = true,GetStatusBarTexture = true,GetStepsPerPage = true,
  GetStringHeight = true,GetStringWidth = true,GetTexCoord = true,GetTexelSnappingBias = true,GetText = true,
  GetTextColor = true,GetTextHeight = true,GetTextInsets = true,GetTextScale = true,GetTexture = true,
  GetTextureFileID = true,GetTextureFilePath = true,GetTextureSliceMargins = true,GetTextureSliceMode = true,
  GetTextWidth = true,GetThickness = true,GetThumbTexture = true,GetTimerDuration = true,GetTop = true,
  GetUnboundedStringWidth = true,GetUnboundedStringWidthForText = true,GetUTF8CursorPosition = true,
  GetValue = true,GetValueStep = true,GetVertexColor = true,GetVertexOffset = true,GetVerticalScroll = true,
  GetVerticalScrollRange = true,GetVertTile = true,GetVisibleTextByteLimit = true,GetWidth = true,
  GetWindow = true,GetWrappedWidth = true,gradient = true,group = true,groups = true,
  HasAccessConstraints = true,hasAccessConstraints = true,hasAlphaGradient = true,HasAlphaGradient = true,
  hasAnyAccessRestriction = true,HasAnyAccessRestrictions = true,hasAnyForbiddenAspect = true,
  HasAnyForbiddenAspects = true,HasAnySecretAspect = true,HasFixedFrameLevel = true,
  HasFixedFrameStrata = true,hasFocus = true,HasFocus = true,hasScript = true,HasScript = true,
  HasSecretAspect = true,hasSecretAspect = true,HasSecretValues = true,hasSecretValues = true,hasText = true,
  HasText = true,height = true,Hide = true,HighlightText = true,HookScript = true,id = true,ignore = true,
  ignoreRect = true,index = true,Insert = true,inside = true,InterceptStartDrag = true,interpolation = true,
  intersects = true,Intersects = true,IsAlphabeticOnly = true,IsAnchoringRestricted = true,
  IsAnchoringSecret = true,IsAutoFocus = true,IsBlockingLoadRequested = true,IsClampedToScreen = true,
  IsCollapsed = true,isCollapsed = true,IsCountInvisibleLetters = true,IsDesaturated = true,isDown = true,
  isDragging = true,IsDragging = true,IsDraggingThumb = true,isDraggingThumb = true,IsDrawLayerEnabled = true,
  IsEnabled = true,isEnabled = true,IsEventRegistered = true,isFixed = true,IsForbidden = true,
  isForbidden = true,IsFrameBuffer = true,isFrameBuffer = true,IsGamePadButtonEnabled = true,
  IsGamePadStickEnabled = true,IsHighlightLocked = true,isIgnoring = true,IsIgnoringChildrenForBounds = true,
  IsIgnoringParentAlpha = true,IsIgnoringParentScale = true,isIndented = true,IsInIMECompositionMode = true,
  isInIMECompositionMode = true,IsInterpolating = true,isInterpolating = true,IsKeyboardEnabled = true,
  isLoaded = true,IsMouseClickEnabled = true,IsMouseEnabled = true,IsMouseMotionEnabled = true,
  isMouseMotionFocus = true,IsMouseMotionFocus = true,isMouseOver = true,IsMouseOver = true,
  IsMouseWheelEnabled = true,isMovable = true,IsMovable = true,IsMultiLine = true,IsNumeric = true,
  isNumeric = true,IsNumericFullRange = true,isObeyStepOnDrag = true,IsObjectLoaded = true,
  IsObjectType = true,isPassword = true,IsPassword = true,isPreventingSecretValues = true,
  IsPreventingSecretValues = true,isProtected = true,IsProtected = true,isProtectedExplicitly = true,
  IsRectValid = true,isRegistered = true,IsResizable = true,isRestricted = true,isReverseFill = true,
  isRolesetFiltered = true,IsRolesetFiltered = true,isSecret = true,isSecure = true,IsSecureText = true,
  isShown = true,IsShown = true,IsSnappingToPixelGrid = true,IsStatusBarDesaturated = true,isTopLevel = true,
  IsToplevel = true,isTruncated = true,IsTruncated = true,isType = true,IsUserPlaced = true,
  isUserPlaced = true,IsUsingParentLevel = true,isValid = true,isVisible = true,IsVisible = true,
  isWithinText = true,iterateAllChildren = true,justifyH = true,justifyV = true,language = true,layer = true,
  left = true,leftIndex = true,length = true,line = true,lineHeight = true,lines = true,llX = true,llY = true,
  location = true,lock = true,locked = true,LockHighlight = true,Lower = true,lrX = true,lrY = true,
  mask = true,maskTexture = true,maxBytes = true,maxColor = true,maxHeight = true,maxLetters = true,
  maxLines = true,maxValue = true,maxVisibleBytes = true,maxWidth = true,minColor = true,minHeight = true,
  minValue = true,minWidth = true,motionScriptsWhileDisabled = true,movable = true,multiline = true,
  name = true,NavigateBack = true,NavigateForward = true,NavigateHome = true,NavigateReload = true,
  NavigateStop = true,normalizedRotationPoint = true,number = true,numChildren = true,numColumns = true,
  numHistoryLines = true,numLetters = true,numLines = true,numPoints = true,numRegions = true,numRows = true,
  obeyStepOnDrag = true,objectTable = true,objectType = true,offset = true,offsetBottom = true,
  offsetLeft = true,offsetRight = true,offsetTop = true,offsetX = true,offsetY = true,OnColorsUpdated = true,
  onUpdateMode = true,OpenExternalLink = true,OpenTicket = true,orientation = true,parent = true,
  parentKey = true,path = true,percent = true,point = true,preferParentKey = true,propagate = true,
  radians = true,Raise = true,range = true,region = true,regions = true,RegisterAllEvents = true,
  registered = true,RegisterEvent = true,RegisterEventCallback = true,RegisterForClicks = true,
  RegisterForDrag = true,RegisterForMouse = true,RegisterUnitEvent = true,RegisterUnitEventCallback = true,
  relativePoint = true,relativeTo = true,RemoveMaskTexture = true,RemoveRoleset = true,renderMode = true,
  ResetInputMode = true,ResetTexCoord = true,resetTexCoords = true,resizable = true,resizePoint = true,
  ResizeToBoundsRect = true,resolveCollapsed = true,restrictions = true,returns = true,reverse = true,
  right = true,rightIndex = true,roleset = true,rolesets = true,rolesetsString = true,rotatesTexture = true,
  RotateTextures = true,scale = true,scaleAnimationMode = true,script = true,scriptName = true,
  scriptTypeName = true,scrollChild = true,SetAllPoints = true,SetAlpha = true,SetAlphabeticOnly = true,
  SetAlphaFromBoolean = true,SetAlphaGradient = true,SetAltArrowKeyMode = true,SetAtlas = true,
  SetAttribute = true,SetAttributeNoHandler = true,SetAutoFocus = true,SetBlendMode = true,
  SetBlinkSpeed = true,SetBlockingLoadsRequested = true,SetButtonState = true,SetChecked = true,
  SetCheckedTexture = true,SetClampedToScreen = true,SetClampRectInsets = true,SetClipsChildren = true,
  SetCollapsesLayout = true,SetColorFill = true,SetColorTexture = true,SetCountInvisibleLetters = true,
  SetCursorPosition = true,SetDesaturated = true,SetDesaturateEmbeddedTextures = true,SetDesaturation = true,
  SetDisabledAtlas = true,SetDisabledCheckedTexture = true,SetDisabledFontObject = true,
  SetDisabledTexture = true,SetDontSavePosition = true,SetDrawLayer = true,SetDrawLayerEnabled = true,
  SetEnabled = true,SetEndPoint = true,SetFillStyle = true,SetFixedColor = true,SetFixedFrameLevel = true,
  SetFixedFrameStrata = true,SetFlattensRenderLayers = true,SetFocus = true,SetFont = true,
  SetFontHeight = true,SetFontObject = true,SetFontString = true,SetForbidden = true,SetFormattedText = true,
  SetFrameLevel = true,SetFrameStrata = true,SetGradient = true,SetHeight = true,SetHighlightAtlas = true,
  SetHighlightColor = true,SetHighlightFontObject = true,SetHighlightLocked = true,SetHighlightTexture = true,
  SetHistoryLines = true,SetHitRectInsets = true,SetHitRectThickness = true,SetHorizontalScroll = true,
  SetHorizTile = true,SetHyperlinkPropagateToParent = true,SetHyperlinksEnabled = true,SetID = true,
  SetIgnoreParentAlpha = true,SetIgnoreParentScale = true,SetIgnoringChildrenForBounds = true,
  SetIndentedWordWrap = true,SetIsFrameBuffer = true,SetJustifyH = true,SetJustifyV = true,SetMask = true,
  SetMaxBytes = true,SetMaxLetters = true,SetMaxLines = true,SetMinMaxValues = true,
  SetMotionScriptsWhileDisabled = true,SetMouseClickEnabled = true,SetMouseMotionEnabled = true,
  SetMovable = true,SetMultiLine = true,SetNonSpaceWrap = true,SetNormalAtlas = true,
  SetNormalFontObject = true,SetNormalTexture = true,SetNumber = true,SetNumeric = true,
  SetNumericFullRange = true,SetObeyStepOnDrag = true,SetOnUpdateMode = true,SetOrientation = true,
  SetParent = true,SetParentKey = true,SetPassThroughButtons = true,SetPassword = true,SetPoint = true,
  SetPointsOffset = true,SetPropagateKeyboardInput = true,SetPropagateMouseClicks = true,
  SetPropagateMouseMotion = true,SetPushedAtlas = true,SetPushedTextOffset = true,SetPushedTexture = true,
  SetRadialProgressBarEndOffset = true,SetRadialProgressBarFeather = true,SetRadialProgressBarPercent = true,
  SetRadialProgressBarReverse = true,SetRadialProgressBarStartOffset = true,SetRenderMode = true,
  SetResizable = true,SetResizeBounds = true,SetReverseFill = true,SetRolesets = true,
  SetRotatesTexture = true,SetRotation = true,SetScale = true,SetScaleAnimationMode = true,SetScript = true,
  SetScrollChild = true,SetSecureText = true,SetSecurityDisablePaste = true,SetSecurityDisableSetText = true,
  SetShadowColor = true,SetShadowOffset = true,SetShown = true,SetSize = true,SetSmoothScaling = true,
  SetSnapToPixelGrid = true,SetSpacing = true,SetSpriteSheetCell = true,SetStartPoint = true,
  SetStatusBarColor = true,SetStatusBarDesaturated = true,SetStatusBarDesaturation = true,
  SetStatusBarTexture = true,SetStepsPerPage = true,SetSVG = true,SetTexCoord = true,
  SetTexelSnappingBias = true,SetText = true,SetTextColor = true,SetTextHeight = true,SetTextInsets = true,
  SetTextScale = true,SetTextToFit = true,SetTexture = true,SetTextureSliceMargins = true,
  SetTextureSliceMode = true,SetThickness = true,SetThumbTexture = true,SetTimerDuration = true,
  SetToDefaults = true,SetToplevel = true,SetToTargetValue = true,SetUserPlaced = true,
  SetUsingParentLevel = true,SetValue = true,SetValueStep = true,SetVertexColor = true,
  SetVertexColorFromBoolean = true,SetVertexOffset = true,SetVerticalScroll = true,SetVertTile = true,
  SetVisibleTextByteLimit = true,SetWidth = true,SetWindow = true,SetWordWrap = true,SetZoom = true,
  ShouldButtonPassThrough = true,shouldPassThrough = true,Show = true,show = true,shown = true,
  SimpleAnimatableObjectAPI = true,SimpleBrowserAPI = true,SimpleButtonAPI = true,SimpleCheckboxAPI = true,
  SimpleEditBoxAPI = true,SimpleFontAPI = true,SimpleFontStringAPI = true,SimpleFrameAPI = true,
  SimpleFrameScriptObjectAPI = true,SimpleLineAPI = true,SimpleMaskTextureAPI = true,SimpleObjectAPI = true,
  SimpleRegionAPI = true,SimpleScriptRegionAPI = true,SimpleScriptRegionResizingAPI = true,
  SimpleScrollFrameAPI = true,SimpleSliderAPI = true,SimpleStatusBarAPI = true,SimpleTextureAPI = true,
  SimpleTextureBaseAPI = true,sliceMode = true,smoothScaling = true,snap = true,sourceFont = true,
  spacing = true,start = true,StartMoving = true,StartSizing = true,stepsPerPage = true,stop = true,
  StopAnimating = true,StopMovingOrSizing = true,strata = true,sublayer = true,subLevel = true,
  sublevel = true,success = true,svgAsset = true,templateName = true,text = true,textScale = true,
  texture = true,textureAsset = true,textureFile = true,thickness = true,tiling = true,
  ToggleInputLanguage = true,top = true,topLevel = true,treatAsMouseEvent = true,ulX = true,ulY = true,
  units = true,UnlockHighlight = true,UnregisterAllEvents = true,UnregisterEvent = true,
  UpdateScrollChildRect = true,urlType = true,urX = true,urY = true,useAtlasSize = true,userPlaced = true,
  usingParentLevel = true,value = true,valueStep = true,vectorGraphics = true,vertexIndex = true,width = true,
  window = true,wordWrap = true,wrap = true,wrapModeHorizontal = true,wrapModeVertical = true,x = true,
  y = true,zoom = true,
}
